// src/features/card-colors/CardColorsSettingsComponent.tsx
import React from 'react';
import Checkbox from 'antd/es/checkbox';
import Tooltip from 'antd/es/tooltip';
import { InfoCircleFilled } from '@ant-design/icons/';
import { Image } from '../../shared/components/Image';
import styles from './CardColorsSettingsComponent.module.css';
import beforeImg from 'src/assets/card-colors-before.jpg';
import afterImg from 'src/assets/card-colors-after.jpg';

type ColorCardFeatureProps = {
  cardColorsEnabled: boolean;
  onCardColorsEnabledChange: (newValue: boolean) => void;
  forceTooltipOpen?: boolean;
};

export const CardColorsSettingsComponent: React.FC<ColorCardFeatureProps> = props => {
  const handleCheckboxChange = (e: any) => {
    props.onCardColorsEnabledChange(e.target.checked);
  };

  return (
    <div className={styles.wrapper}>
      <Checkbox checked={props.cardColorsEnabled} onChange={handleCheckboxChange}>
        Fill whole card
      </Checkbox>
      <Tooltip
        open={props.forceTooltipOpen}
        overlayStyle={{
          // 250 - is default and its small
          maxWidth: 600,
        }}
        title={
          <>
            <p>Feature makes that whole card is colored, instead of just line on left side</p>
            <div className={styles.exampleWithImages}>
              <span className={styles.example}>
                Before
                <Image src={beforeImg} />
              </span>
              <span className={styles.example}>
                After
                <Image src={afterImg} />
              </span>
            </div>
          </>
        }
      >
        <span>
          <InfoCircleFilled style={{ color: '#1677ff' }} />
        </span>
      </Tooltip>
    </div>
  );
};

// src/card-colors/CardColorsSettingsComponent.svelte
<script lang="ts">
  import Checkbox from '../shared/components/Checkbox.svelte';
  import beforeImg from '../assets/card-colors-before.jpg';
  import afterImg from '../assets/card-colors-after.jpg';
  import TooltipWithContent from '../shared/components/TooltipWithContent.svelte';
  import Image from '../shared/components/Image.svelte';

  let count = $state(0);
  setInterval(() => {
    count++;
  }, 1000);
</script>

<div class="jh-flex jh-justify-start">
  <Checkbox label="fill whole card" />
  <TooltipWithContent
    ><p>Feature makes that whole card is colored, instead of just line on left side</p>
    <div class="jh-flex jh-flex-row jh-gap-8">
      <span
        >Before
        <Image src={beforeImg} />
      </span>
      <span
        >After
        <Image src={afterImg} />
      </span>
    </div>
  </TooltipWithContent>
</div>
